### PR TITLE
Replace beecrypt

### PR DESCRIPTION
**Pull request by rolker**
Here's the branch where I replaced beecrypt with Crypto++. It builds on my Ubuntu 18.04 machine, but I haven't tested if the crpyto parts work.

### CODE REVIEW

**Comment by rolker** [comment]
I know just enough about git to be dangerous. I found my old replace_beecrypt branch and rebased it to get the recent changes. I probably should have squashed the commits, but I don't feel like I know how to do that properly.

Also, I'm noticing CI is failing. I'll look into it, but I'd appreciate any help from the experts!

**Comment by rolker** [comment]
Closing this for now until I figure out travis ci and how to squash commits.

**Comment by GlenRice-NOAA** [comment]
Let's check in again next week if you have time.

**Comment by GlenRice-NOAA** [comment]
This pull request appears to break both CIs.  Can you investigate?

**Comment by selimnairb** [comment]
Closing this PR as this branch is no longer valid for the BAG 2.0 codebase.

**Pull request closed without merging**
