### PR TITLE
Travis CI for Linux (Bionic) using gcc, clang, Python 3.6 and 3.7.

### PR DESCRIPTION
**Pull request by jice73**
Also includes very minor code fixes that were necessary to get it compiling on Linux.

### CODE REVIEW

**Comment by GlenRice-NOAA** [comment]
Merge conflicts.

**Comment by vanjulio** [comment]
It looks like this build failure would be fixed if you add  #include <string.h> in bag.cpp? 
I'm not sure why this is showing up in this pull request

**Comment by jice73** [comment]
Sounds right.  That will be next when I see the results of the latest push.

**Comment by jice73** [comment]
Oh, please don't merge this until the Travis CI is green too.

**Comment by GlenRice-NOAA** [comment]
Cool to see green on both Travis and AppVeyor!

**Pull request merged**
